//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Reserva
    {
        [Display(Name = "Codigo de reserva")]
        public int IdReserva { get; set; }
        [Display(Name = "Nombre de Usuario")]
        public string NombreUsuario { get; set; }
        public System.DateTime Fecha { get; set; }
        [Display(Name = "Sede")]
        public int IdSede { get; set; }
        public int Cantidad { get; set; }
        public string Correo { get; set; }
        [Display(Name = "Sede")]
        public virtual Sede Sede { get; set; }
    }
}
